warehouse_management/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from . views import Login, Profile, Registration

app_name = 'accounts'
urlpatterns = [
    path('', Profile.as_view(), name='index'),
    path('login/', Login.as_view(), name='login'),
    path('logout/',
         LogoutView.as_view(next_page='accounts:login'),
         name='logout'
    ),
    path('registration/', Registration.as_view(), name='registration'),
]

warehouse_management/movements/urls.py
from django.urls import path

from .views import ReceiptInvoiceAdd, ReceiptInvoiceList

app_name = 'movements'
urlpatterns = [
    path('add/', ReceiptInvoiceAdd.as_view(), name='add'),
    path('list/', ReceiptInvoiceList.as_view(), name='list'),
]

warehouse_management/warehouse/urls.py
from django.urls import path

from .views import object_list, object_edit, object_add, object_delete

app_name = 'warehouse'
urlpatterns = [
    path('product/list/', object_list, {'entity': 'product'}, name='product_list'),
    path('category/list/', object_list, {'entity': 'category'}, name='category_list'),
    path('provider/list/', object_list, {'entity': 'provider'}, name='provider_list'),
    path('product/add/', object_add, {'entity': 'product'}, name='add_product'),
    path('category/add/', object_add, {'entity': 'category'}, name='add_category'),
    path('provider/add/', object_add, {'entity': 'provider'}, name='add_provider'),
    path('product/<int:pk>/edit/', object_edit, {'entity': 'product'}, name='edit_product'),
    path('category/<int:pk>/edit/', object_edit, {'entity': 'category'}, name='edit_category'),
    path('provider/<int:pk>/edit/', object_edit, {'entity': 'provider'}, name='edit_provider'),
    path('product/<int:pk>/delete/', object_delete, {'entity': 'product'}, name='delete_product'),
    path('category/<int:pk>/delete/', object_delete, {'entity': 'category'}, name='delete_category'),
    path('provider/<int:pk>/delete/', object_delete, {'entity': 'provider'}, name='delete_provider'),
]

warehouse_management/warehouse_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('move/', include('movements.urls')),
    path('warehouse/', include('warehouse.urls')),
]

warehouse_management/templates/add.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
<div class='card col-4'>
  <div class='card-header'>
    {% if '/product/' in request.path %}
      Добавить товар
    {% elif '/category/' in request.path %}
      Добавить категорию
    {% elif '/provider/' in request.path %}
      Добавить поставщика
    {% endif %}
  </div>
  <div class='card-body'>
    <form method='post'>
      {% csrf_token %}
      {% bootstrap_form form %}
      {% bootstrap_button button_type="submit" content="Сохранить" %}
    </form>
    {% endblock content %}

  <div>

warehouse_management/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>

  {% load django_bootstrap5 %}
{% bootstrap_css %}
</head>
<body data-bs-theme="dark">
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Управление складом</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Переключатель навигации">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link {% if '/profile/' in request.path %}active{% endif %}" aria-current="page" href="{% url 'accounts:index' %}">Главная</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle {% if '/warehouse/' in request.path %}active{% endif %}" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Склад
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item {% if '/warehouse/list/' in request.path %}active{% endif %}" href="{% url 'warehouse:product_list' %}">Таблица склада</a></li>
            <li><a class="dropdown-item {% if '/warehouse/list/' in request.path %}active{% endif %}" href="{% url 'warehouse:category_list' %}">Таблица категорий</a></li>
            <li><a class="dropdown-item {% if '/warehouse/list/' in request.path %}active{% endif %}" href="{% url 'warehouse:provider_list' %}">Таблица поставщиков</a></li>
            <li><a class="dropdown-item {% if '/warehouse/product/add/' in request.path %}active{% endif %}" href="{% url 'warehouse:add_product' %}">Добавить товар</a></li>
            <li><a class="dropdown-item {% if '/warehouse/category/add' in request.path %}active{% endif %}" href="{% url 'warehouse:add_category' %}">Добавить категорию</a></li>
            <li><a class="dropdown-item {% if '/warehouse/provider/add' in request.path %}active{% endif %}" href="{% url 'warehouse:add_provider' %}">Добавить поставщика</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle {% if '/move/' in request.path %}active{% endif %}" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Накладные
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'movements:list' %}">Список накладных</a></li>
            <li><a class="dropdown-item" href="{% url 'movements:add' %}">Добавить накладную</a></li>
            <li><a class="dropdown-item" href="{% url 'movements:list' %}">Отчет</a></li>
          </ul>
        </li>

      </ul>
    </div>
  </div>
</nav>
{% block content %}
{% endblock content %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>

</body>
</html>

warehouse_management/templates/confirm_delete.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">
        {% if '/product/' in request.path %}
          Удалить товар
        {% elif '/category/' in request.path %}
          Удалить категорию
        {% elif '/provider/' in request.path %}
          Удалить поставщика
        {% endif %}
      </h5>
      <p class="card-text">Прежде чем удалить, провертье данные</p>
    </div>
    <ul class="list-group list-group-flush">
      {% for field in object.get_fields%}
        <li class="list-group-item">{{field}}</li>
      {% endfor %}
    </ul>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
        </form>
      <a href="{{undo_url}}" class="card-link">Отмена</a>
    </div>
  </div>
{% endblock content %}

warehouse_management/templates/header.html
<nav class="navbar navbar-expand navbar-dark bg-dark" aria-label="Second navbar example">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Always expand</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample02">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
            <ul class="dropdown-menu" aria-labelledby="dropdown04">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
        <form>
          <input class="form-control" type="text" placeholder="Search" aria-label="Search">
        </form>
      </div>
    </div>
  </nav>

warehouse_management/templates/list.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
<table class="table">
  <thead>
    <tr>
      {% for header in headers %}
        <th scope="col">{{header}}</th>
      {% endfor %}
      
    </tr>
  </thead>
  <tbody>
    {% for object in object_list %}
    <tr>
      {% for product in object.get_fields%}
        <td>{{product}}</td>
      {% endfor %}
      <td scope="col">
        <a href="{{path}}{{object.id}}/edit/" class="btn btn-warning btn-sm"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
          <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325"/>
        </svg></a>
        <a href="{{path}}{{object.id}}/delete/" class="btn btn-danger btn-sm"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
          <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5"/>
        </svg></a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}