warehouse_management/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from . views import Login, Profile, Registration

app_name = 'accounts'
urlpatterns = [
    path('', Profile.as_view(), name='index'),
    path('login/', Login.as_view(), name='login'),
    path('logout/',
         LogoutView.as_view(next_page='accounts:login'),
         name='logout'
    ),
    path('registration/', Registration.as_view(), name='registration'),
]

warehouse_management/warehouse_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('move/', include('movements.urls')),
    path('warehouse/', include('warehouse.urls')),
]

warehouse_management/accounts/views.py
from django.shortcuts import render, HttpResponseRedirect,redirect
from django.views import View
from django.urls import reverse
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User




class Profile(View):
    template = 'accounts/profile.html'
    
    def get(self, request):
        if request.user.is_authenticated:
            return render(request, self.template)
        else:
            return HttpResponseRedirect(reverse('accounts:login'))


class Login(View):
    template = 'accounts/login.html'

    def get(self, request):
        form = AuthenticationForm()
        context = {
            'form': form,
        }
        return render(request, self.template, context)
    
    def post(self, request):
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return HttpResponseRedirect(reverse('accounts:index'))


class Registration(View):
    template = 'accounts/registration.html'

    def get(self, request):
        form = UserCreationForm()
        context = {
            'form': form,
        }
        return render(request, self.template, context)
    
    def post(self, request):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('accounts:login')

warehouse_management/templates/accounts/index.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
<h1>Добро пожаловать на страницу вашего аккаунта!!!</h1>
<p>Имя пользователя: {{user.username}}</p>
<p>Дата регистрации: {{user.date_joined}}</p>

<a href="{% url 'accounts:logout' %}">Выйти</a>

warehouse_management/templates/accounts/login.html
<!-- Ваш_проект/ваш_приложение/templates/login.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>

    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        form {
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            padding: 20px;
            width: 300px;
            text-align: left;
        }

        label {
            display: block;
            margin-bottom: 8px;
        }

        input {
            width: 100%;
            padding: 8px;
            margin-bottom: 16px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        button {
            background-color: #4caf50;
            color: #fff;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        button:hover {
            background-color: #45a049;
        }

        .error {
            color: red;
            margin-bottom: 16px;
        }
    </style>
</head>
<body>
    <form method="post" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        <h2>Login</h2>

        {% if error %}
            <p class="error">{{ error }}</p>
        {% endif %}

        {{ form.as_p }}

        <!-- <label for="username">Username:</label>
        <input type="text" name="username" required>

        <label for="password">Password:</label>
        <input type="password" name="password" required> -->

        <button type="submit">Login</button>
        <a href="{% url "accounts:registration" %}">Зарегистрироваться</a>
    </form>
</body>
</html>

warehouse_management/templates/accounts/profile.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
<h1>{{ request.user }}</h1>
<h2>Дата регистрации: {{ request.user.date_joined }}</h2>
<h2>Дата последнего входа: {{ request.user.last_login }}</h2>
<a href="{% url 'accounts:logout' %}">Выйти</a><br>
{% endblock content %}

warehouse_management/templates/accounts/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>

    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        form {
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            padding: 20px;
            width: 300px;
            text-align: left;
        }

        label {
            display: block;
            margin-bottom: 8px;
        }

        input {
            width: 100%;
            padding: 8px;
            margin-bottom: 16px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        button {
            background-color: #4caf50;
            color: #fff;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        button:hover {
            background-color: #45a049;
        }

        .error {
            color: red;
            margin-bottom: 16px;
        }
    </style>
</head>
<body>
    <form method="post" action="{% url 'accounts:registration' %}" method="post">
        {% csrf_token %}
        <h2>Регистрация</h2>

        {% if error %}
            <p class="error">{{ error }}</p>
        {% endif %}

        {{ form.as_p }}

        <!-- <label for="username">Username:</label>
        <input type="text" name="username" required>

        <label for="password">Password:</label>
        <input type="password" name="password" required> -->

        <button type="submit">Зарегистрироваться</button>
        <a href='{% url 'accounts:login' %}'>Войти</a>
    </form>
</body>
</html>