warehouse_management/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from . views import Login, Profile, Registration

app_name = 'accounts'
urlpatterns = [
    path('', Profile.as_view(), name='index'),
    path('login/', Login.as_view(), name='login'),
    path('logout/',
         LogoutView.as_view(next_page='accounts:login'),
         name='logout'
    ),
    path('registration/', Registration.as_view(), name='registration'),
]

warehouse_management/movements/urls.py
from django.urls import path

from .views import ReceiptInvoiceAdd, ReceiptInvoiceList

app_name = 'movements'
urlpatterns = [
    path('add/', ReceiptInvoiceAdd.as_view(), name='add'),
    path('list/', ReceiptInvoiceList.as_view(), name='list'),
]

warehouse_management/warehouse/urls.py
from django.urls import path

from .views import object_list, object_edit, object_add, object_delete

app_name = 'warehouse'
urlpatterns = [
    path('product/list/', object_list, {'entity': 'product'}, name='product_list'),
    path('category/list/', object_list, {'entity': 'category'}, name='category_list'),
    path('provider/list/', object_list, {'entity': 'provider'}, name='provider_list'),
    path('product/add/', object_add, {'entity': 'product'}, name='add_product'),
    path('category/add/', object_add, {'entity': 'category'}, name='add_category'),
    path('provider/add/', object_add, {'entity': 'provider'}, name='add_provider'),
    path('product/<int:pk>/edit/', object_edit, {'entity': 'product'}, name='edit_product'),
    path('category/<int:pk>/edit/', object_edit, {'entity': 'category'}, name='edit_category'),
    path('provider/<int:pk>/edit/', object_edit, {'entity': 'provider'}, name='edit_provider'),
    path('product/<int:pk>/delete/', object_delete, {'entity': 'product'}, name='delete_product'),
    path('category/<int:pk>/delete/', object_delete, {'entity': 'category'}, name='delete_category'),
    path('provider/<int:pk>/delete/', object_delete, {'entity': 'provider'}, name='delete_provider'),
]

warehouse_management/warehouse_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('move/', include('movements.urls')),
    path('warehouse/', include('warehouse.urls')),
]

warehouse_management/movements/models.py
from django.db import models
from django.utils import timezone

STATUS_CHOICES = (
        ('add', 'Добаленно'),
        ('move', 'Прошло'),
    )

class ReceiptInvoice(models.Model):
    date_creation = models.DateTimeField(
        default=timezone.now,
        verbose_name='Дата создания'
    )
    date_move = models.DateTimeField(
        blank=True,
        null=True,
        verbose_name='Дата проверки'
    )
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='новая',
        verbose_name='Статус'
    )

warehouse_management/movements/forms.py
from django.forms import ModelForm
from .models import ReceiptInvoice

class ReceiptInvoiceForm(ModelForm):
    class Meta:
        model = ReceiptInvoice
        fields = '__all__'

warehouse_management/movements/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.edit import FormView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .forms import ReceiptInvoiceForm
from .models import ReceiptInvoice

class ReceiptInvoiceAdd(FormView):
    template_name = 'add.html'
    form_class = ReceiptInvoiceForm
    success_url = reverse_lazy('movements:list')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

class ReceiptInvoiceList(ListView):
    template_name = 'movements/list.html'
    model = ReceiptInvoice
    context_object_name = 'products'
    
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

warehouse_management/templates/movements/add.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
<div class='card col-4'>
  <div class='card-header'>
    {% if '/product/' in request.path %}
      Добавить товар
    {% elif '/category/' in request.path %}
      Добавить категорию
    {% elif '/provider/' in request.path %}
      Добавить поставщика
    {% endif %}
  </div>
  <div class='card-body'>
    <form method='post'>
      {% csrf_token %}
      {% bootstrap_form form %}
      {% bootstrap_button button_type="submit" content="Сохранить" %}
    </form>
    {% endblock content %}

  <div>

warehouse_management/templates/movements/list.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Код накладной</th>
      <th scope="col">Дата создания</th>
      <th scope="col">Дата провередния</th>
      <th scope="col">Статус</th>
    </tr>
  </thead>
  <tbody>
    {% for product in products %}
     <tr>
       <td scope="col">{{product.id}}</td>
       <td scope="col">{{product.date_creation}}</td>
       <td scope="col">{{product.date_move}}</td>
       <td scope="col">{{product.status}}</td>
       <td scope="col">
        <a href="{% url "warehouse:edit_product" pk=product.id %}" class="btn btn-warning btn-sm"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
          <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325"/>
        </svg></a>
        <a href="{% url "warehouse:delete_product" pk=product.id %}" class="btn btn-danger btn-sm"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
          <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5"/>
        </svg></a></td>
    </tr>
    {% endfor %}
   
  </tbody>
</table>

{% endblock content %}